### PR TITLE
added an inv_total field to the invoices table, editinvoice and listi…

### PR DESCRIPTION
**Pull request by Longshot123**
…nvoices. 

This pull request adds a total (inv_total) field to the Invoices database, (Total: $) on the invoice edit page and (Invoice Total) on the invoice list page. I created it in the database with the dataType TEXT, but it could be Numeric as well. SQLite didn't seem to have a good decimal datatype. I found that with using text it was pretty easy to remove any special characters like $ and , before performing any calculations on the values. 

I updated the sqlite.txt and added 5_6a.sql script to create/add the new inv_total table column for invoices. I could not find whether these were manually ran or if it was called from somewhere when you first install itdb.  I named the new script 5_6b.sql instead of 7_8.sql to avoid any conflict later on my end, if the pull is not excepted. 

Tim

First, pull request, so I hope I did this correctly.

### CODE REVIEW

**Comment by Chefkeks** [comment]
Would like to see this merged as well :)
Any feedback from you @sivann ?

**Comment by Chefkeks** [comment]
@Longshot123
Some screenshots would be nice ;)

**Comment by Longshot123** [comment]
The total field added to the editInvoice page
addedtotal2invoice

ListInvoice page with added invoice total column
listinvoicepage

Added a report to list all invoices, by contract, with the contract number, name, and purchase total as a line separator between contracts
listposbycontract

--------------------------------
I also added a ostype, checksumtype, and some added software info. I use a lot of VMs inventoried as items, which some hold a lot of third-party software. So, I personally have to track the checksum, OS type of the software, and the web location where it is stored on the VM. 
I haven't had time to figure out your CSS code on the list software page to add the extra column fields. 

added software info section
softwareinfo

ostypes
ostypes

chksum types
cksumtypes

added links
addedlinks


I added a couple small changes that list the purchase date column when connecting software to items and added contract number to the listing when connecting invoices to contracts to make it easier to tell contracts apart. 

Let me know if you need some more explanation of what I have done on my end.

**Comment by sivann** [comment]
Hi I will return back at September and review. Thanks.

**Comment by Longshot123** [comment]
I didn't realize that all the commits into my dev branch made after my pull request gets pushed into the pull request until Michael asked for screenshots. Still learning. I have been real busy, but will try to check for areas that are not as generic as they should be for everyone during this next week.

**Comment by sivann** [comment]
Hello,
thank you for your pull req; I don't think this can be merged for those reasons:

* ITDB is an inventory software. The invoices section is solely for quick warranty reference. ITDB should not aims to duplicate financial software functionality, that would just clutter the UI as the result will be always a half-finished unusable finance s/w. I try to adhere to the  "dotadiw," rule :-)
* OS Type. I think this can be served well by "software vendor"
* URLs, Checksums; I'm not sure I understood what these are about, but I believe you can just add them to the "Description" field. Separate fields are added for relations and sepecific search needs. Not for UI enrichment.
Kind Regards,
-Spiros

**Pull request closed without merging**
