### PR TITLE
Themes for ITDB

### PR DESCRIPTION
**Pull request by Chefkeks**
Hi @sivann 

we are working on several improvements for ITDB.
This is our first improvement which allows themes for ITDB.

Would be great if you can include this into official ITDB. Hope you agree with the changes/additions and the way we implemented it. When you disagree with some of the changes, please let us know or modify it on your own, so it can be included to official ITDB.

Since we are planning to provide more improvements in the near future, it would be great to receive some feedback to make sure our effort is worth it and that our custom changes are merged with official ITDB so everyone who is using it can benefit from these changes.

Thanks in advance,
@Chefkeks and @slicki

### CODE REVIEW

**Comment by Chefkeks** [comment]
Oops, guess we forgot to update SQL.txt and some screenshots would have been nice too. Adding stuff tomorrow :)

**Comment by sivann** [comment]
Sorry not interested in keeping several themes up to date. Only adding important functionality changes at this time. You may always use your custom .css file in your installation.
Regards,
-Spiros

**Comment by sivann** [comment]
Please note that my time is very limited and as much as I would like to add all your suggestions, I get a lot of support emails for ITDB, more than I can handle. So each new thing will add more support request which I am not currently able to cover.
Regards,
-Spiros

**Comment by djzort** [comment]
It seems that the popularity of ITDB has surpassed one persons time to support. I think that speaks wonders to the software itself and its creator! Perhaps the best way forward is to create a github 'group' and allow co-authors to assist in support, vetting pull requests and adding new features?

**Comment by Chefkeks** [comment]
Sounds like a reasonable idea to me, but I think that decision is up to @sivann as he is the creator of ITDB.

**Pull request closed without merging**
