### PR TITLE
Added features and functionality

### PR DESCRIPTION
**Pull request by fud18**
Added Departments, VLANS, Jacks, and Projects pages.

Added delete button on list pages.

### CODE REVIEW

**Comment by Chefkeks** [comment]
Can you provide some screenshots please?

I am not the developer of osTicket, but we also develop further our ITDB. 

Unfortunately the developer seems not to accept any pull request (see #37), which I can understand, but some more functions and features would be nice. So we decided to make a new branch for every feature we (@TeamSF with members @slicki and @Chefkeks) develop and will soon provide more pull requests (like #39). We also keep a master branch with all changes we made, that are already working without any found bugs. You can view at our branches here: https://github.com/TeamSF/itdb-green/branches/all

So based on the experience with older pull requests (see closed pull requests) this hopefully seems to be better as one pull request which combines many features, so the developer can decide easier what to include and also maintain it easier.

So, it's just a guess, but I think this pull request won't be accepted for the reason and also since it includes several files that seem to come from a sync software which definitely should not be part of the ITDB files.

Anyway, we would love to see some screenshots for all the changes and new features you made.

Cheers,
Patrick (@slicki) and Michael (@Chefkeks)
(@TeamSF)

**Comment by fud18** [comment]
Which files are the sync files you found?

**Comment by Chefkeks** [comment]
For example /_notes/dwsync.xml and also there is still the phpliteadmin.php which shall not be included in such a pull request I think.

**Comment by fud18** [comment]
Not sure why the dwsync file is there and I'll remove it, but I left phpliteadmin for the reason that I thought it would be a nice addition so that people could work on their databases.

Cory Funk | Assistant Network Coordinator
FORT HAYS STATE UNIVERSITY
415 Lyman Dr. TH 101, Hays, KS 67601
(785) 628-4054 | cafunk@fhsu.edu

Sent from my Android phone.

**Comment by subarusyd** [comment]
Hi fud18 ,

Thanks for this amazing piece of addition to ITDB. I have been using ITDB and find it as an amazing piece of software. Your amazing additions just completes it perfectly. Can you please advise how can I use this additions with my existing ITDB installation? Currently its fresh blank installation at the moment so I can start afresh if needed.  

 I am new to ITDB so please bear with me if I seem a bit uninformed.  Eagerly looking forward to your reply.

cheers
MIc

**Comment by fud18** [comment]
You should be able to replace your current website pages with the new.  For the database I would use the enclosed phpliteadmin and dump your current database info into the new database included in the new download.  Hope this helps.  If you have any more questions feel free to email me.

Cory

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Thanks Cory. I have downloaded the zip of all these files and was just wondering is there any instructions to how to integrate this to the existing itdb installation. its fresh so there is no data in it at the moment.??!!

**Comment by fud18** [comment]
The best way would just be to totally replace everything with the new then and rename pure.db with itdb.db like when you first set it up.

Cory

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Go it. Thanks so much. Have a very nice day :)

**Comment by fud18** [comment]
You too and enjoy the improvements I have a couple more coming and I am working on a couple of fixes as well.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Cool thanks. Mate you are a legend :)

**Comment by subarusyd** [comment]
Hi Cory, got that  overwritten and its shows me projects, vlans ,and departments. just curious is there any way to show new department, vlan fields in the item list attributes page?! I am trying to do is modify the import.php so that I can import department as well from my csv  sheet. so was wondering how can we display the Department, vlan field info in the Item View and Item attributes page?!

Thanks

**Comment by fud18** [comment]
It should just be a matter of updating the code on that page to pull in the info.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Cool. Will Do. Thanks for all your replies and support. very kind of you.

**Comment by fud18** [comment]
Anytime.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
sorry to bother you, can I ask which page/s are the one I should be looking to change for the Item attributes and the View?!

**Comment by fud18** [comment]
For the item attributes you want the edititems.php and for the List you want the listitems.php-----subarusyd <notifications@github.com> wrote: -----To: sivann/itdb <itdb@noreply.github.com>From: subarusyd <notifications@github.com>Date: 11/15/2015 06:19PMCc: Cory Funk <cafunk@fhsu.edu>Subject: Re: [itdb] Added features and functionality (#40)sorry to bother you, can I ask which page/s are the one I should be looking to change for the Item attributes and the View?!

**Comment by subarusyd** [comment]
Million thanks

**Comment by subarusyd** [comment]
Hi, 
I have managed to get it all integrated and seems to log in fine too. The main page shows departments, vlan, projects, and jack output fine. But when i click on the plus symbol to add i just get these errrors as mentioned below. i have been trying to figure out all day today but cant seem to. It seems the database table does not exist for these?!! Do i need to create these tables manually via a sqlite3 gui front end tool. Or is it an error in my integration of the new files??!!

When i click on Jacks, it just refreshes the current web page and returns to itself and shows a blank blue screen web page without any error.?! Any ideas?!

Thanks 
Mic



For Departments:

db_execute:DB Error: (SELECT * FROM departments WHERE id='new'): no such table: departments

Array
(
    [0] => Array
        (
            [file] => /var/www/html/itdb/php/editdepartment.php
            [line] => 98
            [function] => db_execute
            [args] => Array
                (
                    [0] => PDO Object
                        (
                        )

                    [1] => SELECT * FROM departments WHERE id='new'
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/itdb/index.php
            [line] => 487
            [args] => Array
                (
                    [0] => /var/www/html/itdb/php/editdepartment.php
                )

            [function] => require
        )

)



FOR VLANS:


db_execute:DB Error: (SELECT * from vlans order by id): no such table: vlans

Array
(
    [0] => Array
        (
            [file] => /var/www/html/itdb/php/listvlans.php
            [line] => 60
            [function] => db_execute
            [args] => Array
                (
                    [0] => PDO Object
                        (
                        )

                    [1] => SELECT * from vlans order by id
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/itdb/index.php
            [line] => 487
            [args] => Array
                (
                    [0] => /var/www/html/itdb/php/listvlans.php
                )

            [function] => require
        )

)



FOR PROJECTS:

db_execute:DB Error: (SELECT * FROM projects WHERE id='new'): no such table: projects

Array
(
    [0] => Array
        (
            [file] => /var/www/html/itdb/php/editproject.php
            [line] => 132
            [function] => db_execute
            [args] => Array
                (
                    [0] => PDO Object
                        (
                        )

                    [1] => SELECT * FROM projects WHERE id='new'
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/itdb/index.php
            [line] => 487
            [args] => Array
                (
                    [0] => /var/www/html/itdb/php/editproject.php
                )

            [function] => require
        )

)

Fatal error: Call to a member function fetch() on a non-object in /var/www/html/itdb/php/editproject.php on line 133

**Comment by subarusyd** [comment]
Hi, 

Sorry to bother you. figured out it was a database issue. anyways as soon i fix that it stops me at the logon page with this error. it does not log me in at all and does not let me go in. hit a wall. 

would greatly appreciate any assistance when you have some spare time. have a nice day.

cheers
Mic

image

**Comment by fud18** [comment]
I will check it out as soon as I can for you.

Cory

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Thanks. just some more info if it helps!!. :)

 As soon as i change the itdb back to the default original db it lets me log in and it shows all the new PHP web pages. its only happens when i use that pure.db database renaming it to itdb.db.

image
 
image

**Comment by fud18** [comment]
Did you make sure to set your permissions on the pure.db after you renamed it?

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Yes, i believe so. it seems right?!! 
image

**Comment by subarusyd** [comment]
please ignore the rest of the files. i am using itdb.db

**Comment by fud18** [comment]
Looks like you are having problems with the text file in the translations folder.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
oh ok. is there anything i can do to fix it?!

**Comment by fud18** [comment]
Not sure off the top of my head.  I will try and check it out.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Hi,
was wondering if its possible for you to upload a entire working ITDB folder with all your amazing updates off a fresh working installation as a zip file somewhere so that i can just download it and dump it into the fresh VM ubuntu /var/www/html/ location and that should do get me up and running?!! 
thanks
MIc

**Comment by fud18** [comment]
That's exactly what my git upload is.  It is just a zipped version.  I have reloaded it on my severs a couple of times.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
oh ok. sorry but just to confirm here are the steps i was using.?!
(a)  Download zip file from https://github.com/fud18/itdb
(b)  use winscp to transfer the file to the ubuntu vm. 
(c)  overwrite everything sudo cp -a /home/sydneyit/itdb-master/* /var/www/html/itdb/ -v
(d) sudo chown -R www-data:www-data /var/www/html/itdb/    (as the permissions are overwritten as sydneyit;fixes the permission)
(e) cd /var/www/html/itdb/data
(f) sudo mv pure.db itdb.db
cd..
(g) sudo chmod 777 /var/www/html/itdb/data/itdb.db
(h)sudo chmod -R 755 ./var/www/html/itdb/data/
(i) sudo chmod 755 /var/www/html/itdb/translations/
(j) sudo chown www-data:www-data -R itdb/data/files/
(k) sudo chmod u+w itdb/data/files/

This is what i used for original installation for ITDB and it works for the original installation though!!
Thanks
mic

**Comment by fud18** [comment]
That should be right.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Hmmm. ok. i will start with a fresh new ubunut 14.0 vm and a fresh itdb installation and then use this procedure up above with the new zip file contents. 

BTW do you have any VM OVF virtual appliance uploaded somewhere with this full ITDB installation? ?!

**Comment by fud18** [comment]
I don't because it is our production server at work.  Sorry.  Have you tried using CentOS.

That is what I am using and it has been great.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
oh ok. thanks. hopefully i will get this working this time. <fingerscrossed>

**Comment by fud18** [comment]
No problem...hope it works out for you.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by fud18** [comment]
One thing I forgot to mention...if you are going to try CentOS I would use the 6.x version.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
oh ok thanks. i have never used Centos. always stuck with ubuntu. but if i do i will definitely try that version. :)

**Comment by subarusyd** [comment]
Hi Cory,
Gud Morning.
had no luck still stuck at the same problem. but in order to suffice the basic needs, i have managed to change the Item attributes web page so that i can use 'function' field as department and 'sn2' as leased/purchased from items table. also successfully managed to fix the import.php to further extend import functionality for these fields. 

i have managed to modify the items "View" to replace the ipv6 and the remadmip as   Department(function field value) and Leased/purchased(sn2 field value) by editing itemlists.php.  what i am stuck at is that i cannot figure out how to show these field values there?!. it still showing the values for ipv6 and remadmip.?!! Any ideas how to?!

Thanks
cheers
mic

image

**Comment by fud18** [comment]
If you download my latest push from this afternoon it has the features I believe you were asking for.  I listed them in the git documentation.  Let me know

Cory

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Oh Cool. Thanks. i will check it out. The main request what the helpdesk guys are asking for is the ITEMS view to show these feilds so that they can view then and sort them the way they need. 

Also, i noticed that the items view page seems to be divided into two parts. It seems to show the top bar and headers from the itemlists.php and the data from the itemlists2.php. but just out of curiosity what needs to be edited to update these Item View data repective to the headers in listitems.php?!

**Comment by fud18** [comment]
Itemslist has no search where itemslist2 does, but if you are actually using my version I did away with that and just use itemslist.   Judging by your screens hot it doesn't look like you are using my fork of itdb, but if you are you will now have the option to search and sort by department abbreviation and vlan when you hit more on the itemslist page.

Cory


Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
yep. i could not get it to work. i fixed the translation error and then try to login but it failed as Invalid username. Then using sqliteadmin i figured out that it did not have any users in it. so populated with  the command line sqlite3 sql commands. it logs me in  and then it advises me to Update. i click on update and thats where it gets stuck. Have done the fresh installation 3 times but every time it gets stuck here. Had managed to use the original db from sivan itdb 1.22 and then manually insert create the missing tables in there such as projects,departments,jacks,vouchers,etc... it lets me in and it seems to work almost but the home page is a bit skewed. You have done an amazing job and its really good but it seems the fruits of that labour is not in my destiny :) not giving up though.!!

image
image
image

**Comment by fud18** [comment]
Would you be opposed to me removing in to your server to see what I can figure out.  I can give you a login to my screenconnect server for a one time access if you are OK with it.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
really appreciate that. i can give teamviewer access to you if you like?!!  i will private email you the details if you are ok with it?!

**Comment by fud18** [comment]
That would be fine, but team viewer only let's me go for 5 minutes the disconnects me, because it was detected that I was using for business purposes.

Try this

http://screenconnect.fud.homelinux.net:8040

Choose ITDB
password  ueok

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
no luck. my firewalls blocking it. it seems. do you wanna try teamviewer? maybe lucky 5 mins is all we might need ?!! :)

**Comment by fud18** [comment]
Sure

Sent from my Android phone using Symantec TouchDown (www.symantec.com)


-----Original Message-----

**Comment by subarusyd** [comment]
Hi Cory,
afternoon. how you been? i managed to fix the index.php by overwriting with an earlier version of yours and it all seems to be working perfectly. Thanks zillions for all your help. Also, i have managed to modify the import.php script and fix the CPU,RAM,HD import part of it. The final part to this amazing solution is i was wondering on how to modify the import.php in such a way that i can also import the department fields such as department name and department abbr from CSV for the items i intend to import. i am working on it atm and hope to get that working. Any ideas or suggestions would be great!! . Once i have a final setup, if you like, I can transfer these final ITDB folder+contents to you to upload to github so that anybody with Ubuntu installation will have this working seamlessly with no issues at all.

Thanks 
Mic

**Comment by fud18** [comment]
I haven't worked much with the import.php file as I have doen all of my upload info with the enclosed phpliteadmin file.  I will do CSV uploads straight to the database, but of you get ot
 working I would definitely be interested in it...thanks for the update 
and I am glad it is working for you.  I hope you are enjoying the 
product.Cory -----subarusyd <notifications@github.com> wrote: -----To: sivann/itdb <itdb@noreply.github.com>From: subarusyd <notifications@github.com>Date: 11/24/2015 10:16PMCc: Cory Funk <cafunk@fhsu.edu>Subject: Re: [itdb] Added features and functionality (#40)Hi Cory,
afternoon. how you been? i managed to fix the index.php by overwriting with an earlier version of yours and it all seems to be working perfectly. Thanks zillions for all your help. Also, i have managed to modify the import.php script and fix the CPU,RAM,HD import part of it. The final part to this amazing solution is i was wondering on how to modify the import.php in such a way that i can also import the department fields such as department name and department abbr from CSV for the items i intend to import. i am working on it atm and hope to get that working. Any ideas or suggestions would be great!! . Once i have a final setup, if you like, I can transfer these final ITDB folder+contents to you to upload to github so that anybody with Ubuntu installation will have this working seamlessly with no issues at all.

Thanks 
Mic

**Comment by subarusyd** [comment]
yep. i love it. its amazing especially with your additions in there. i am still testing the import function but i will email you the final import.php file with my changes in it. I think i will end up doing the same thing where I will use the Phpliteadmin to import the data using csv . The final thing I am actually working on is how to modify the Items View such as that I can include the Label, users,function, software, warranty info, etc..  This ones a bit hard but i will see how i go. Also, when you click on the delete link, it will pop up and you click "YES"  and Click OK. it will refresh the page but it does not delete the item. Looking into that as well. I really appreciate your additions and help.

Cheers
Mic

**Comment by kris1977** [comment]
Hello,

is there a way to add software while adding items. at this moment i must exit the add item and go to add software and start over again adding the item to associate the software. 

how do the other people associate every sepperat windows license whit every sepparet item?

**Comment by sivann** [comment]
Guys thank you for your interest in ITDB. This pull request thread is way out of the scope of a pull request. If you want to add your own features/functionality except those requested or customize it for your companies, please feel free to fork the project! The pull request of github will not work for either ITDB or your needs.
Regards,
-S

**Pull request closed without merging**
